import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import HomeComponent from "@/components/HomeComponent";
import Footer from "@/components/Footer";
import Testimonial from "@/components/Feedback/TestimonialSection";
import { productsGetAll } from "@/utlis/productsApis";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });


export async function getServerSideProps() {
  const data = await productsGetAll();
  return {
    props: {
      products: data
    }
  }
}



export default function Home({ products }) {


  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent {...products} />
      {/* <Testimonial /> */}
      {/* <Footer /> */}
    </div>
  );
}
